import test from 'node:test';
import assert from 'node:assert/strict';
import { randomBytes } from 'node:crypto';
import { createStore } from '../server/store.mjs';
import { createApp } from '../server/app.mjs';
const event = (kind, id, text, seconds = 0) => ({ kind, eventId: id, externalId: 'message-1', scope: 'chat-1', chatId: 'chat-1', chatName: 'Friends', authorName: 'Alice', text, occurredAt: new Date(Date.now() - 60_000 + seconds * 1000).toISOString() });
async function fixture(t) {
  const store = createStore(':memory:', randomBytes(32).toString('hex'));
  t.after(() => store.close());
  const user = await store.createUser('alice', 'a-strong-password-123');
  const connection = store.createConnection(user.id, 'discord', 'Server');
  const source = store.connectionByToken(connection.token);
  return { store, user, connection, source };
}
test('archives create → edit → delete and keeps both content versions encrypted', async t => {
  const { store, user, source } = await fixture(t);
  const original = event('create', 'a', 'meet at seven');
  const edited = event('edit', 'b', 'meet at eight', 10);
  store.ingest(source, original); store.ingest(source, edited); store.ingest(source, event('delete', 'c', undefined, 20));
  const [message] = store.messages(user.id);
  assert.equal(message.status, 'deleted'); assert.equal(message.text, 'meet at eight');
  assert.deepEqual(message.versions.map(v => v.text), ['meet at seven', 'meet at eight', undefined]);
  assert.equal(message.originalMissing, false);
  const raw = JSON.stringify(store.db.prepare('SELECT payload FROM events').all());
  assert.equal(raw.includes('meet at'), false); assert.equal(raw.includes('Alice'), false);
  assert.equal(store.ingest(source, original).duplicate, true);
  assert.equal(store.messages(user.id)[0].versions.length, 3);
});
test('out-of-order deliveries fill gaps without resurrecting a deleted message', async t => {
  const { store, user, source } = await fixture(t);
  store.ingest(source, event('delete', 'delete', undefined, 30));
  store.ingest(source, event('edit', 'edit', 'newer', 20));
  assert.equal(store.messages(user.id)[0].originalMissing, true);
  store.ingest(source, event('create', 'create', 'original', 0));
  store.ingest(source, event('edit', 'older-edit', 'older', 10));
  const [message] = store.messages(user.id);
  assert.equal(message.status, 'deleted'); assert.equal(message.text, 'newer');
  assert.equal(message.originalMissing, false);
  assert.deepEqual(message.versions.map(v => v.kind), ['create', 'edit', 'edit', 'delete']);
});
test('same external IDs are isolated across connections and message scopes', async t => {
  const { store, user, source } = await fixture(t);
  const other = await store.createUser('bob', 'a-strong-password-456');
  const otherSource = store.connectionByToken(store.createConnection(other.id, 'telegram', 'Private').token);
  store.ingest(source, event('create', 'a', 'alice secret'));
  store.ingest(otherSource, event('create', 'a', 'bob secret'));
  store.ingest(source, { ...event('create', 'a2', 'other room'), scope: 'chat-2' });
  assert.equal(store.messages(user.id).length, 2); assert.equal(store.messages(other.id).length, 1);
  assert.equal(store.message(store.messages(other.id)[0].id, user.id), null);
});
test('paused and ephemeral events are excluded', async t => {
  const { store, user, source } = await fixture(t);
  assert.equal(store.ingest({ ...source, paused: 1 }, event('create', 'a', 'paused')).ignored, true);
  assert.equal(store.ingest(source, { ...event('create', 'b', 'ephemeral'), ephemeral: true }).ignored, true);
  assert.equal(store.messages(user.id).length, 0);
});
test('retention purges saved messages too and prevents replay from restoring them', async t => {
  const { store, user, source } = await fixture(t);
  const first = event('create', 'a', 'old'); const { id } = store.ingest(source, first);
  store.db.prepare('UPDATE messages SET saved=1,first_seen=? WHERE id=?').run(new Date(Date.now() - 91 * 86400_000).toISOString(), id);
  store.purge(); assert.equal(store.messages(user.id).length, 0);
  assert.equal(store.ingest(source, first).reason, 'removed');
});
test('permanent message deletion removes revisions and suppresses future retries', async t => {
  const { store, user, source } = await fixture(t);
  const original = event('create', 'a', 'remove'); const { id } = store.ingest(source, original);
  store.forgetMessage(id, user.id);
  assert.equal(store.db.prepare('SELECT count(*) n FROM events').get().n, 0);
  assert.equal(store.ingest(source, event('edit', 'b', 'also remove')).reason, 'removed');
});
test('API enforces session auth, source token scope, CSRF and revocation', async t => {
  const { store, user, connection } = await fixture(t);
  const server = createApp(store, { origins: ['http://localhost'] }).listen(0, '127.0.0.1');
  await new Promise(resolve => server.once('listening', resolve));
  t.after(() => new Promise(resolve => server.close(resolve)));
  const base = `http://127.0.0.1:${server.address().port}/api`;
  const request = async (path, method = 'GET', body, headers = {}) => fetch(base + path, { method, headers: { ...(body ? { 'Content-Type': 'application/json' } : {}), ...headers }, body: body ? JSON.stringify(body) : undefined });
  assert.equal((await request('/messages')).status, 401);
  const login = await request('/auth/login', 'POST', { username: 'alice', password: 'a-strong-password-123' });
  assert.equal(login.status, 200); const cookie = login.headers.get('set-cookie').split(';')[0];
  assert.match(login.headers.get('set-cookie'), /HttpOnly/); assert.match(login.headers.get('set-cookie'), /SameSite=Strict/);
  assert.equal((await request('/connections', 'GET', undefined, { Cookie: cookie })).status, 200);
  const list = await (await request('/connections', 'GET', undefined, { Cookie: cookie })).json();
  assert.equal(JSON.stringify(list).includes(connection.token), false);
  const events = [event('create', 'a', 'original'), event('edit', 'b', 'new', 10), event('delete', 'c', undefined, 20)];
  assert.equal((await request('/ingest', 'POST', { events }, { Authorization: `Bearer ${cookie}` })).status, 401);
  const result = await (await request('/ingest', 'POST', { events }, { Authorization: `Bearer ${connection.token}` })).json();
  assert.equal(result.results.length, 3); assert.ok(result.results.every(r => r.id));
  const own = await (await request('/messages?q=original', 'GET', undefined, { Cookie: cookie })).json();
  assert.equal(own.total, 1); assert.equal(own.messages[0].status, 'deleted');
  const other = await store.createUser('eve', 'a-strong-password-789'); const otherCookie = `afterword=${store.session(other.id)}`;
  assert.equal((await request(`/messages/${own.messages[0].id}`, 'GET', undefined, { Cookie: otherCookie })).status, 404);
  assert.equal((await request('/connections', 'POST', { platform: 'signal', name: 'test' }, { Cookie: cookie, Origin: 'https://evil.invalid' })).status, 403);
  await request(`/connections/${connection.id}`, 'DELETE', {}, { Cookie: cookie });
  assert.equal((await request('/ingest', 'POST', { events }, { Authorization: `Bearer ${connection.token}` })).status, 401);
  await request('/auth/logout', 'POST', {}, { Cookie: cookie });
  assert.equal((await request('/messages', 'GET', undefined, { Cookie: cookie })).status, 401);
});
test('retention removes large expired batches atomically and honours a time budget', async t => {
  const { store, user, source } = await fixture(t);
  const old = new Date(Date.now() - 91 * 86400_000).toISOString();
  for (let i = 0; i < 1203; i++) store.ingest(source, { ...event('create', 'e' + i, 'expired ' + i), externalId: 'm' + i, scope: 'chat-1' });
  store.ingest(source, { ...event('create', 'fresh', 'keep'), externalId: 'fresh', scope: 'chat-1' });
  store.db.prepare("UPDATE messages SET first_seen=? WHERE id IN (SELECT id FROM messages WHERE user_id=? ORDER BY id LIMIT 1203)").run(old, user.id);
  assert.equal(store.purge({ budgetMs: -1 }), false, 'a spent budget stops before finishing');
  assert.equal(store.db.prepare('SELECT count(*) n FROM messages WHERE user_id=?').get(user.id).n, 1204, 'nothing is deleted once the budget is spent');
  assert.equal(store.purge(), true);
  assert.equal(store.db.prepare('SELECT count(*) n FROM messages WHERE user_id=?').get(user.id).n, 1);
  assert.equal(store.db.prepare('SELECT count(*) n FROM forgotten WHERE user_id=?').get(user.id).n, 1203);
  assert.equal(store.db.prepare('SELECT count(*) n FROM events').get().n, 1);
  assert.equal(store.ingest(source, { ...event('create', 'e7', 'expired 7'), externalId: 'm7', scope: 'chat-1' }).reason, 'removed');
  assert.equal(store.db.prepare("SELECT name FROM sqlite_master WHERE type='index' AND name='messages_retention'").get()?.name, 'messages_retention');
});
test('edits that leave text and attachments unchanged are acknowledged but not recorded as versions', async t => {
  const { store, user, source } = await fixture(t);
  const count = () => store.db.prepare('SELECT count(*) n FROM events').get().n;
  store.ingest(source, event('create', 'a', 'meet at seven'));
  // A reaction, link preview, pin, or formatting change arrives as an edit with the same content.
  assert.deepEqual(store.ingest(source, event('edit', 'b', 'meet at seven', 5)), { ignored: true, reason: 'unchanged', id: store.messages(user.id)[0].id });
  let [message] = store.messages(user.id);
  assert.equal(count(), 1); assert.equal(message.status, 'captured'); assert.equal(message.versionCount, 1);
  assert.equal(store.ingest(source, event('edit', 'b', 'meet at seven', 5)).reason, 'unchanged', 'a retry stays ignored');
  assert.equal(store.ingest(source, event('edit', 'c', 'meet at eight', 10)).duplicate, false, 'a real text change is recorded');
  assert.equal(store.ingest(source, event('edit', 'd', 'meet at eight', 15)).reason, 'unchanged');
  assert.equal(store.ingest(source, { ...event('edit', 'e', 'meet at eight', 20), attachments: [{ name: 'map.png', type: 'image/png' }] }).duplicate, false, 'an attachment change is recorded');
  assert.equal(store.ingest(source, event('edit', 'f', 'meet at seven', 25)).duplicate, false, 'reverting to earlier text is a change from the current version');
  [message] = store.messages(user.id);
  assert.equal(count(), 4); assert.equal(message.versionCount, 4); assert.equal(message.status, 'edited');
  assert.deepEqual(message.versions.map(v => v.text), ['meet at seven', 'meet at eight', 'meet at eight', 'meet at seven']);
  store.ingest(source, event('delete', 'g', undefined, 30));
  assert.equal(store.ingest(source, event('edit', 'h', 'meet at seven', 35)).duplicate, false, 'an edit after a deletion tombstone is still preserved');
  assert.equal(store.ingest(source, event('edit', 'i', 'brand new', 1)).duplicate, false, 'a late edit with different text is preserved');
});
test('only deleted messages leave the watch buffer; held messages expire after the owner\'s watch window', async t => {
  const { store, user, source } = await fixture(t);
  const at = minutes => new Date(Date.now() - minutes * 60_000).toISOString();
  const first = store.ingest(source, { ...event('create', 'a', 'kept for now'), externalId: 'held', occurredAt: at(5) });
  assert.equal(first.held, true);
  store.ingest(source, { ...event('create', 'b', 'gone for good'), externalId: 'removed', occurredAt: at(5) });
  const removed = store.ingest(source, { ...event('delete', 'c', undefined), externalId: 'removed', occurredAt: at(4) });
  assert.equal(removed.held, false);
  assert.equal(store.ingest(source, { ...event('delete', 'd', undefined), externalId: 'never-seen', occurredAt: at(3) }).held, false, 'a tombstone alone is archived');
  const listed = await store.listMessages(user.id);
  assert.deepEqual(listed.messages.map(m => [m.externalId, m.originalMissing, m.text]).sort(), [['never-seen', true, ''], ['removed', false, 'gone for good']]);
  assert.equal(listed.stats.held, 1); assert.equal(listed.stats.total, 2);
  assert.equal(await store.messageHistory(first.id, user.id), null, 'held messages have no history page');
  let text = ''; for await (const chunk of store.exportArchive(user.id)) text += chunk;
  assert.deepEqual(JSON.parse(text).messages.map(m => m.externalId).sort(), ['never-seen', 'removed']);
  assert.equal(store.connections(user.id)[0].message_count, 2); assert.equal(store.connections(user.id)[0].held_count, 1);
  // The watch window is measured from the last activity, per user.
  store.db.prepare('UPDATE users SET hold_days=1 WHERE id=?').run(user.id);
  store.db.prepare("UPDATE messages SET last_seen=? WHERE id=?").run(at(60 * 25), first.id);
  assert.equal(store.purge(), true);
  assert.equal(store.messages(user.id).length, 2, 'the expired held message is discarded, deleted ones stay');
  assert.equal(store.ingest(source, { ...event('delete', 'e', undefined), externalId: 'held', occurredAt: at(1) }).held, false, 'a late deletion still records a tombstone without content');
  assert.equal((await store.listMessages(user.id)).messages.find(m => m.externalId === 'held').originalMissing, true);
});
test('the watch window is an account setting with fixed choices', async t => {
  const { store, user } = await fixture(t);
  const { createApp } = await import('../server/app.mjs');
  const server = createApp(store, { origins: ['http://localhost'] }).listen(0, '127.0.0.1');
  await new Promise(r => server.once('listening', r)); t.after(() => new Promise(r => server.close(r)));
  const base = `http://127.0.0.1:${server.address().port}/api`, headers = { 'Content-Type': 'application/json', Cookie: `afterword=${store.session(user.id)}` };
  assert.equal(store.getUser(user.id).hold_days, 7);
  const ok = await fetch(base + '/settings', { method: 'PATCH', headers, body: JSON.stringify({ holdDays: 3 }) });
  assert.equal(ok.status, 200); assert.equal((await ok.json()).user.hold_days, 3);
  assert.equal((await fetch(base + '/settings', { method: 'PATCH', headers, body: JSON.stringify({ holdDays: 5 }) })).status, 400);
  assert.equal((await fetch(base + '/settings', { method: 'PATCH', headers, body: JSON.stringify({}) })).status, 400);
  assert.equal((await fetch(base + '/settings', { method: 'PATCH', headers, body: JSON.stringify({ retentionDays: 30 }) })).status, 200);
  assert.equal(store.getUser(user.id).hold_days, 3); assert.equal(store.getUser(user.id).retention_days, 30);
});
