import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, readdirSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomBytes, createHmac } from 'node:crypto';
import { createBackup } from '../server/backup.mjs';
import { createStore } from '../server/store.mjs';
import { openQueue } from '../companion/queue.mjs';
test('online backups restore encrypted archive revisions and collector sessions without copying keys', async t => {
  const dir = mkdtempSync(join(tmpdir(), 'afterword-backup-')), key = randomBytes(32).toString('hex');
  t.after(() => rmSync(dir, { recursive: true, force: true }));
  const store = createStore(join(dir, 'afterword.sqlite'), key), user = await store.createUser('owner', 'long-test-password');
  const c = store.createConnection(user.id, 'telegram', 'Cloud'), source = store.connectionByToken(c.token);
  store.ingest(source, { eventId: 'one', kind: 'create', externalId: '1', scope: 'account', text: 'private archive message', occurredAt: new Date().toISOString() });
  const derived = createHmac('sha256', Buffer.from(key, 'hex')).update('afterword-hosted:' + c.id).digest('hex');
  const queue = openQueue(join(dir, 'collectors', c.id), derived); queue.set('telegram-session', 'private session data');
  const snapshot = await createBackup(dir, { keep: 1 });
  assert.equal(snapshot.keyIncluded, false); assert.equal(snapshot.files.length, 2);
  const restored = createStore(join(snapshot.directory, 'afterword.sqlite'), key);
  assert.equal(restored.messages(user.id)[0].text, 'private archive message');
  const restoredQueue = openQueue(join(snapshot.directory, 'collectors', c.id), derived);
  assert.equal(restoredQueue.get('telegram-session'), 'private session data');
  assert.equal(readFileSync(join(snapshot.directory, 'afterword.sqlite')).includes(Buffer.from('private archive message')), false);
  restoredQueue.close(); restored.close();
  await createBackup(dir, { keep: 1 });
  assert.equal(readdirSync(join(dir, 'backups')).filter(n => !n.startsWith('.')).length, 1);
  queue.close(); store.close();
});
test('low disk space aborts a backup without removing the last complete recovery snapshot', async t => {
  const dir = mkdtempSync(join(tmpdir(), 'afterword-backup-space-')), key = randomBytes(32).toString('hex');
  const store = createStore(join(dir, 'afterword.sqlite'), key);
  t.after(() => { store.close(); rmSync(dir, { recursive: true, force: true }); });
  await store.createUser('owner', 'long-test-password');
  const complete = await createBackup(dir);
  await assert.rejects(createBackup(dir, { minimumFreeBytes: 10000, availableBytes: () => 10000 }), { code: 'disk_capacity' });
  assert.deepEqual(readdirSync(join(dir, 'backups')), [complete.directory.split('/').at(-1)]);
  assert.equal(JSON.parse(readFileSync(join(complete.directory, 'manifest.json'))).format, 1);
});
