import { chromium, expect } from '@playwright/test';
import { randomBytes } from 'node:crypto';
import { mkdirSync, readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
const base = process.env.TEST_URL || 'http://127.0.0.1:5178';
const output = resolve(process.env.TEST_OUTPUT || '/tmp/afterword-browser');
mkdirSync(output, { recursive: true });
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const issues = [];
page.on('pageerror', e => issues.push(e.message));
const username = `test-${randomBytes(6).toString('hex')}`;
const password = randomBytes(20).toString('base64url');
let created = false;
try {
  await page.goto(base);
  await expect(page.getByRole('heading', { name: 'Message archive.' })).toBeVisible();
  await expect(page.locator('.message-row')).toHaveCount(8);
  await page.screenshot({ path: join(output, 'desktop.png'), fullPage: true });
  await page.getByLabel('View history of message from Maya Chen').click();
  await expect(page.getByText('Original message', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Compare changes' }).click();
  await expect(page.locator('.diff-removed')).toContainText('Thursday');
  await expect(page.locator('.diff-added')).toContainText('Friday');
  await page.screenshot({ path: join(output, 'history.png'), fullPage: true });
  await page.getByLabel('Close history').click();
  await page.getByLabel('Search messages').fill('Table booked');
  await expect(page.locator('.message-row')).toHaveCount(1);
  await page.getByLabel('Clear search').click();
  await page.getByLabel('Filter by platform').selectOption('signal');
  await expect(page.locator('.message-row')).toHaveCount(2);
  await page.getByLabel('Filter by platform').selectOption('');
  await page.getByRole('button', { name: 'Create your archive' }).click();
  await page.getByLabel('Username', { exact: true }).fill(username);
  await page.getByLabel('Password', { exact: true }).fill(password);
  if (await page.getByLabel('Invitation code').count()) {
    if (!process.env.TEST_INVITE_FILE) throw new Error('Set TEST_INVITE_FILE for an invite-only server.');
    await page.getByLabel('Invitation code').fill(readFileSync(process.env.TEST_INVITE_FILE, 'utf8').trim());
  }
  await page.getByRole('button', { name: 'Create account', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Your connections.' })).toBeVisible(); created = true;
  await expect(page.locator('.demo-banner')).toHaveCount(0);
  await page.getByRole('button', { name: 'Connect Discord', exact: true }).click();
  await page.locator('dialog input[type=checkbox]').check();
  await page.getByRole('button', { name: 'Continue to setup', exact: true }).click();
  const code = await page.getByLabel('Pairing code', { exact: true }).innerText();
  const pairResponse = await page.request.post(`${base}/api/pair`, { data: { code } });
  const { connection } = await pairResponse.json();
  const key = connection.token;
  const download = page.waitForEvent('download');
  await page.getByRole('link', { name: 'Download companion ZIP' }).click();
  const downloaded = await download; await downloaded.saveAs(join(output, 'companion.zip'));
  await page.request.post(`${base}/api/heartbeat`, { headers: { Authorization: `Bearer ${key}` }, data: { health: 'connected', detail: 'Browser test collector' } });
  await expect(page.getByRole('heading', { name: 'Discord is connected', exact: true })).toBeVisible({ timeout: 10000 });
  const now = Date.now() - 10_000;
  const event = (kind, index, text) => ({ eventId: `ui-${index}`, kind, externalId: 'ui-test', scope: 'room', chatId: 'room', chatName: 'Browser test', authorName: 'Test sender', text, occurredAt: new Date(now + index * 1000).toISOString() });
  const ingest = await page.request.post(`${base}/api/ingest`, { headers: { Authorization: `Bearer ${key}` }, data: { events: [event('create', 1, 'The original appointment is Tuesday.'), event('edit', 2, 'The appointment is Wednesday.'), event('delete', 3)] } });
  expect(ingest.ok()).toBeTruthy();
  await page.getByRole('button', { name: /(?:Go to|Open) my archive/ }).click();
  await page.getByRole('button', { name: 'All messages', exact: true }).click();
  await expect(page.locator('.message-row')).toHaveCount(1);
  await page.getByLabel('View history of message from Test sender').click();
  await expect(page.getByText('Your captured copy is still in your archive.')).toBeVisible();
  await expect(page.getByText('The original appointment is Tuesday.', { exact: true })).toBeVisible();
  await page.getByLabel('Save selected message').click();
  await expect(page.getByLabel('Unsave selected message')).toBeVisible();
  await page.getByLabel('Close history').click();
  await page.getByLabel('Search messages').fill('Tuesday');
  await expect(page.locator('.message-row')).toHaveCount(1);
  const exportData = await (await page.request.get(`${base}/api/export`)).json();
  expect(exportData.messages[0].versions.length).toBe(3);
  expect(exportData.messages[0].saved).toBe(true);
  await page.screenshot({ path: join(output, 'real-archive.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: join(output, 'mobile.png'), fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.getByLabel('View history of message from Test sender').click();
  await expect(page.getByText('Message history', { exact: true })).toBeVisible();
  await page.screenshot({ path: join(output, 'mobile-history.png'), fullPage: true });
  await page.getByLabel('Close history').click();
  await page.getByLabel('Toggle navigation').click();
  await page.getByRole('button', { name: 'Connections', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Your connections.' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  expect(issues).toEqual([]);
  console.log('PASS: demo, history/diff, search, platform filters, real signup, connection creation, companion download, ingestion, bookmarks, export, mobile layout/navigation; no browser errors.');
} finally {
  if (created) await page.request.delete(`${base}/api/account`, { data: { password } });
  await browser.close();
}
