import React, { useState } from 'react';
import { Copy, Download, KeyRound } from 'lucide-react';
export function RecoveryKey({ value, Modal, onDone }) {
  const [saved, setSaved] = useState(false), [error, setError] = useState('');
  function download() {
    const url = URL.createObjectURL(new Blob([`undelete.chat account recovery key\n\n${value}\n\nKeep this in a password manager or another private place. It can reset your undelete.chat password. Each use replaces it with a new key.\n`], { type: 'text/plain' }));
    const a = document.createElement('a'); a.href = url; a.download = 'afterword-recovery-key.txt'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
  }
  return <Modal title="Save your recovery key" onClose={onDone}><div className="section-icon"><KeyRound size={22}/></div><p className="modal-description">Use this key to reset your undelete.chat password if you forget it. We show it only now. Save it somewhere private, such as your password manager.</p><code className="recovery-key">{value}</code><div className="wizard-actions"><button className="button secondary" onClick={() => navigator.clipboard.writeText(value).catch(() => setError('Select the key above and copy it manually.'))}><Copy size={15}/>Copy key</button><button className="button secondary" onClick={download}><Download size={15}/>Download key</button></div><label className="checkbox-label"><input type="checkbox" checked={saved} onChange={e => setSaved(e.target.checked)}/><span>I’ve saved my recovery key somewhere private.</span></label>{error && <p role="alert" className="form-error">{error}</p>}<button className="button primary full" disabled={!saved} onClick={onDone}>Continue</button></Modal>;
}
export function RecoveryForm({ Modal, api, onRecovered, onClose }) {
  const [busy, setBusy] = useState(false), [error, setError] = useState('');
  return <Modal title="Recover your account" onClose={onClose}><p className="modal-description">Enter the recovery key you saved when setting up your account. It also unlocks your sealed archive on this device. Your linked accounts and archive will remain; other undelete.chat sessions will be signed out.</p><form onSubmit={async e => { e.preventDefault(); const body = Object.fromEntries(new FormData(e.currentTarget)); setBusy(true); setError(''); try { await onRecovered(await api('/auth/recover', { method: 'POST', body }), body); } catch (e) { setError(e.message); } finally { setBusy(false); } }}><label>Username<input name="username" autoComplete="username" required/></label><label>Recovery key<input name="recoveryKey" type="password" autoComplete="off" required/></label><label>New password<input name="password" type="password" autoComplete="new-password" minLength={12} maxLength={128} required/></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="button primary full" disabled={busy}>Reset password</button></form></Modal>;
}
