import React, { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, CheckCheck, ChevronRight, CircleHelp, Clock3, Copy, Download, ExternalLink, LoaderCircle, Monitor, Radio, RefreshCw } from 'lucide-react';
import { platformGuides, platformOrder, discordBrowserGuide } from './guides.mjs';

const isLive = c => c && (c.platform !== 'discord' || c.collector === 'discord-browser') && !c.revoked && !c.paused && c.health === 'connected' && Date.now() - Date.parse(c.last_seen) < 90_000;
function CodeBlock({ children, label = 'Copy command' }) {
  const [copied, setCopied] = useState(false), [failed, setFailed] = useState(false);
  async function copy() { try { await navigator.clipboard.writeText(children); setCopied(true); setFailed(false); setTimeout(() => setCopied(false), 2000); } catch { setFailed(true); } }
  return <div className="command-wrap"><div className="command-block"><pre>{children}</pre><button className="icon-button" aria-label={label} onClick={copy}>{copied ? <Check size={16}/> : <Copy size={16}/>}</button></div>{failed && <small>Select the text above and copy it manually.</small>}</div>;
}
export function LocalConnectionWizard({ initialPlatform, initialConnection, Modal, Platform, api, onClose, onFinish, onChanged }) {
  const [platform, setPlatform] = useState(initialConnection?.platform || initialPlatform || null);
  const [connection, setConnection] = useState(initialConnection || null);
  const [step, setStep] = useState(initialConnection ? isLive(initialConnection) ? 3 : 2 : initialPlatform ? 1 : 0);
  const [name, setName] = useState(initialConnection?.name || (initialPlatform ? `My ${platformGuides[initialPlatform].name}` : ''));
  const [pairing, setPairing] = useState(null), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const [now, setNow] = useState(Date.now());
  const [os, setOs] = useState(/Windows/i.test(navigator.userAgent) ? 'windows' : /Mac/i.test(navigator.userAgent) ? 'mac' : 'linux');
  const info = platform === 'discord' ? discordBrowserGuide : platform && platformGuides[platform];
  const guideSlug = platform === 'discord' ? 'discord-extension' : platform;
  const profile = connection ? `${connection.platform}-${connection.id.slice(0, 8)}` : '';
  const npm = os === 'windows' ? 'npm.cmd' : 'npm';
  const pairingCommand = `${npm} start -- pair --server ${window.location.origin}`;
  const paired = connection?.paired_at && (platform !== 'discord' || connection.collector === 'discord-browser') && (!pairing || connection.paired_at >= pairing.createdAt);
  const expired = pairing && now >= Date.parse(pairing.expiresAt);
  const captured = connection?.last_message_at && (!connection.paired_at || connection.last_message_at >= connection.paired_at);
  useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer); }, []);
  useEffect(() => {
    if (!connection?.id || info?.available === false) return;
    let active = true;
    const check = async () => { try {
      const result = await api('/connections');
      const updated = result.connections.find(c => c.id === connection.id);
      if (!active || !updated) return;
      setConnection(updated);
      if (isLive(updated) && (!pairing || updated.paired_at >= pairing.createdAt)) setStep(3);
    } catch { /* A transient poll error should not interrupt the setup form. */ } };
    check(); const timer = setInterval(check, 3000);
    return () => { active = false; clearInterval(timer); };
  }, [connection?.id, pairing?.createdAt]);
  async function generate(existing = connection) {
    if (info?.available === false) return;
    setBusy(true); setError('');
    try {
      const c = existing || (await api('/connections', { method: 'POST', body: { platform, name } })).connection;
      setConnection(c); onChanged();
      const result = await api(`/connections/${c.id}/pairing`, { method: 'POST', body: {} });
      setPairing(result.pairing); setStep(2);
    } catch (e) { setError(e.message); } finally { setBusy(false); }
  }
  const title = step === 0 ? 'Choose your first connection' : step === 3 ? `${info.name} connection check` : `Connect ${info.name}`;
  return <Modal title={title} wide onClose={onClose}>
    {step > 0 && <ol className="setup-progress" aria-label="Connection setup progress">{['Check access', 'Pair companion', 'Verify capture'].map((label, i) => <li key={label} className={step === i + 1 ? 'current' : step > i + 1 ? 'complete' : ''} aria-current={step === i + 1 ? 'step' : undefined}><span>{step > i + 1 ? <Check size={12}/> : i + 1}</span>{label}</li>)}</ol>}
    {step === 0 && <><p className="modal-description">Start with an account you use every day. You can add the others whenever you’re ready.</p><div className="platform-choices">{platformOrder.map(p => <button key={p} onClick={() => { setPlatform(p); setName(`My ${platformGuides[p].name}`); setStep(1); }}><Platform platform={p}/><span><strong>{platformGuides[p].name}</strong><small>{platformGuides[p].effort}</small></span><ChevronRight size={18}/></button>)}</div><div className="setup-footnote"><Monitor size={16}/><span>Setup needs a computer. Discord uses a browser extension; the other platforms use a terminal. Your archive works on your phone afterward.</span></div></>}
    {step === 1 && <><div className="wizard-platform"><Platform platform={platform}/><div><strong>{info.name}</strong><span>{info.mode}</span></div><a href={`/docs/${guideSlug}`} target="_blank" rel="noreferrer">Full guide <ExternalLink size={13}/></a></div><p className="modal-description">{info.coverage}</p><div className="prerequisite-card"><h3>Have these ready</h3><ul>{info.needs.map(n => <li key={n}><Check size={14}/>{n}</li>)}</ul><a href={`/docs/${guideSlug}#platform-setup`} target="_blank" rel="noreferrer">Where to find these <ArrowRight size={13}/></a></div><form onSubmit={e => { e.preventDefault(); generate(); }}><label>Connection name<input value={name} onChange={e => setName(e.target.value)} maxLength={100} required placeholder={`My ${info.name}`}/></label><label className="checkbox-label"><input type="checkbox" required/><span>I’m authorized to archive these conversations and understand that captured copies can remain after deletion.</span></label>{error && <p role="alert" className="form-error">{error}</p>}<div className="wizard-actions"><button type="button" className="button secondary" onClick={() => setStep(0)}><ArrowLeft size={15}/>Back</button><button type="submit" className="button primary" disabled={busy}>{busy ? <LoaderCircle size={15} className="spin"/> : null}Continue to setup<ArrowRight size={15}/></button></div></form><p className="wizard-smallprint">{info.exclusions}</p></>}
    {step === 2 && platform === 'discord' && <>
      <div className="wizard-platform"><Platform platform="discord"/><div><strong>{connection.name}</strong><span>Personal Discord · browser extension</span></div><a href="/docs/discord-extension" target="_blank" rel="noreferrer">Full guide<ExternalLink size={13}/></a></div>
      <div className="wizard-step"><span className="step-marker">1</span><div><h3>Install the browser extension</h3><p>Download and extract the ZIP. In Chrome, open <strong>chrome://extensions</strong>, turn on Developer mode, and choose <strong>Load unpacked</strong>. Select the extracted <strong>afterword-discord-extension</strong> folder.</p><a className="button secondary" href="/api/discord/extension"><Download size={16}/>Download Discord extension</a><p className="wizard-smallprint">Chrome 125+ required. This experimental extension uses debugging permission to observe incoming messages in the Discord tab you choose. It does not need your Discord password or token.</p></div></div>
      <div className="wizard-step"><span className="step-marker">2</span><div><h3>Pair with your archive</h3><p>Open the Afterword extension from Chrome’s Extensions menu. Enter this server address and your pairing code.</p><CodeBlock label="Copy archive address">{window.location.origin}</CodeBlock>{paired ? <p className="paired-note"><Check size={16}/>The extension is paired with this source.</p> : pairing && !expired ? <div className="pair-code-box"><span className="pair-code" aria-label="Pairing code">{pairing.code}</span><button className="icon-button" aria-label="Copy pairing code" onClick={() => navigator.clipboard.writeText(pairing.code).catch(() => setError('Select the code and copy it manually.'))}><Copy size={17}/></button><small>Expires in {Math.max(0, Math.ceil((Date.parse(pairing.expiresAt) - now) / 60_000))} min · use once</small></div> : <button className="button secondary" disabled={busy} onClick={() => generate()}>Generate pairing code</button>}</div></div>
      <div className="wizard-step"><span className="step-marker">3</span><div><h3>Choose your Discord tab</h3><p>Sign in to Discord Web as usual. In the extension, choose that tab and click <strong>Start capturing DMs</strong>. The tab reloads once; send or clear any draft first. Keep the tab and Chrome’s debugging notice open.</p><a href="https://discord.com/channels/@me" target="_blank" rel="noreferrer">Open Discord Web <ExternalLink size={13}/></a></div></div>
      <div className={`pairing-status ${connection.health === 'error' ? 'attention' : ''}`} role="status"><Radio size={18}/><div><strong>{connection.health === 'error' ? 'The extension needs attention' : paired ? 'Waiting for Discord capture' : 'Waiting for your extension'}</strong><p>{connection.health === 'error' ? connection.detail : 'This screen updates when the extension observes your personal Discord session.'}</p></div></div>
      {error && <p role="alert" className="form-error">{error}</p>}<details className="resume-help"><summary>Already paired or need a new code?</summary><p>Use Start capturing DMs in the extension to resume. To pair again, stop and disconnect the old extension connection first. A new code replaces this source’s archive key after redemption.</p><button className="button secondary" disabled={busy} onClick={() => generate()}>Generate a new code</button></details><p className="wizard-smallprint">{info.exclusions}</p><div className="wizard-actions"><a href="/docs/discord#fixes" target="_blank" rel="noreferrer">Troubleshooting</a><button className="button secondary" onClick={onClose}>Finish later</button></div>
    </>}
    {step === 2 && platform !== 'discord' && <>
      <div className="wizard-platform"><Platform platform={platform}/><div><strong>{connection.name}</strong><span>{paired ? 'Paired with your computer' : 'Ready to pair'}</span></div><a href={`/docs/${guideSlug}`} target="_blank" rel="noreferrer">Open guide <ExternalLink size={13}/></a></div>
      <div className="os-switch" aria-label="Computer operating system">{[['mac', 'macOS'], ['windows', 'Windows'], ['linux', 'Linux']].map(([value, label]) => <button key={value} aria-pressed={os === value} onClick={() => setOs(value)}>{label}</button>)}</div>
      <div className="wizard-step"><span className="step-marker">1</span><div><h3>Install the companion</h3><p>Install <a href="https://nodejs.org/en/download" target="_blank" rel="noreferrer">Node.js LTS</a> (22.13 or newer), then download and extract this ZIP.</p><a className="button secondary" href="/api/companion/download?format=zip"><Download size={16}/>Download companion ZIP</a><details><summary>How do I open the folder in a terminal?</summary><p>{os === 'mac' ? 'Open Terminal. Type cd followed by a space, drag the extracted afterword-companion folder into the window, then press Return.' : os === 'windows' ? 'Extract the ZIP first. Inside the afterword-companion folder, right-click an empty area and choose Open in Terminal. The commands use npm.cmd to avoid PowerShell script-policy errors.' : 'In your file manager, open the extracted afterword-companion folder and choose Open in Terminal, or use cd to reach it.'}</p></details><CodeBlock label="Copy install command">{`${npm} ci --omit=dev`}</CodeBlock></div></div>
      <div className="wizard-step"><span className="step-marker">2</span><div><h3>{paired ? 'Finish the platform sign-in' : 'Pair it with your archive'}</h3>{paired ? <div className="paired-note"><Check size={17}/><span>The companion has paired. Follow its {info.name} prompts in the terminal.</span></div> : <><p>Run this command, then paste the short code when the terminal asks.</p><CodeBlock label="Copy pairing command">{pairingCommand}</CodeBlock>{pairing && !expired ? <div className="pair-code-box"><span className="pair-code" aria-label="Pairing code">{pairing.code}</span><button className="icon-button" aria-label="Copy pairing code" onClick={() => navigator.clipboard.writeText(pairing.code).catch(() => setError('Select the pairing code and copy it manually.'))}><Copy size={17}/></button><small><Clock3 size={12}/>Expires in {Math.min(10, Math.max(0, Math.ceil((Date.parse(pairing.expiresAt) - now) / 60_000)))} min · use once</small></div> : <div className="pair-code-empty"><p>{expired ? 'This code expired. Generate another to continue.' : 'Generate a fresh code when your terminal is ready.'}</p><button className="button primary" disabled={busy} onClick={() => generate()}><RefreshCw size={14}/>Generate pairing code</button></div>}</>}
      <details className="platform-instructions" open={!!paired}><summary>{info.name} sign-in instructions</summary><ol>{info.finish.map(s => <li key={s}>{s}</li>)}</ol>{info.resources.map(r => <a href={r.url} key={r.url} target="_blank" rel="noreferrer">{r.label} <ExternalLink size={11}/></a>)}</details></div></div>
      <div className={`pairing-status ${connection.health === 'error' ? 'attention' : ''}`} role="status"><Radio size={19}/><div><strong>{connection.health === 'error' ? 'Your companion needs attention' : paired ? 'Waiting for platform sign-in' : 'Waiting for your companion'}</strong><p>{connection.health === 'error' ? connection.detail || 'Check the terminal for the next step.' : 'This screen updates automatically. Keep the companion running.'}</p></div></div>
      <details className="resume-help"><summary>Already paired, or need to start again?</summary><p>To resume an existing profile, use:</p><CodeBlock label="Copy resume command">{`${npm} start -- run ${profile}`}</CodeBlock><p>Older manual setups use their original profile name.</p><p>To pair again, stop the old companion first. A new pairing replaces its archive key while keeping your history.</p><button className="button secondary" onClick={() => generate()} disabled={busy}>Generate a new code</button><a href="/docs/troubleshooting#relink" target="_blank" rel="noreferrer">Platform unlinked your device? Read the relinking guide.</a></details>
      {error && <p role="alert" className="form-error">{error}</p>}<div className="wizard-actions"><a href="/docs/troubleshooting" target="_blank" rel="noreferrer"><CircleHelp size={15}/>Need a hand?</a><button className="button secondary" onClick={onClose}>Finish later</button></div><p className="wizard-smallprint">Your progress is saved. Reopen this source from Connections to continue.</p>
    </>}
    {step === 3 && <><div className={`verification-hero ${isLive(connection) ? 'connected' : ''}`}><span>{isLive(connection) ? <CheckCheck size={28}/> : <Radio size={28}/>}</span><h3>{isLive(connection) ? `${info.name} is connected` : 'The companion is currently offline'}</h3><p>{isLive(connection) ? 'Now make sure a message reaches your archive.' : platform === 'discord' ? 'Open the extension and click Start capturing DMs.' : 'Keep the computer awake and use the Resume command in Connections.'}</p></div><div className="verify-checklist"><div className="done"><Check size={16}/><span>{platform === 'discord' ? 'Extension' : 'Companion'} paired with your workspace</span></div><div className={isLive(connection) ? 'done' : ''}><Check size={16}/><span>{info.name} session connected</span></div><div className={captured ? 'done' : ''}>{captured ? <Check size={16}/> : <Clock3 size={16}/>}<span>{captured ? 'A message has reached your archive' : 'Waiting for your first captured message'}</span></div></div><div className="test-message-card"><h3>Try a message you can recognize</h3><ol><li>Send <strong>Afterword connection test</strong> in a covered conversation.</li><li>Wait for it to appear, then edit it and check its history.</li><li>Delete it in the original app to check deletion capture.</li></ol><p>Use your own test message. Afterword does not send anything for you.</p></div><p className="wizard-smallprint">{info.exclusions} Deletions appear only when the platform delivers the event.</p><div className="wizard-actions"><a href={`/docs/${guideSlug}#fixes`} target="_blank" rel="noreferrer">Not seeing a message?</a><button className="button primary" onClick={() => onFinish(connection)}>{captured ? 'Open my archive' : 'Go to my archive'}<ArrowRight size={16}/></button></div><div className="setup-footnote"><Monitor size={16}/><span>{platform === 'discord' ? 'Keep Chrome and your selected Discord Web tab open.' : 'Leave the companion running. Your browser can be closed.'}</span></div></>}
  </Modal>;
}
