import React, { useEffect, useState } from 'react';
import { ArrowRight, BellRing, Clock3, RefreshCw, Search, Smartphone, Trash2 } from 'lucide-react';
import { deviceArchive } from './native.mjs';

// "On this phone": the Android device mode. Everything shown here comes from
// the phone's own database, filled by the notification listener. Nothing is
// sent to the server, and no sign-in is needed to read it.
const apps = { 'com.whatsapp': 'WhatsApp', 'com.whatsapp.w4b': 'WhatsApp Business', 'org.telegram.messenger': 'Telegram', 'org.telegram.messenger.web': 'Telegram', 'org.thoughtcrime.securesms': 'Signal' };
const when = ms => new Date(ms).toLocaleString([], { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' });
export function DeviceArchive({ Modal, notify }) {
  const plugin = deviceArchive();
  const [status, setStatus] = useState(null), [rows, setRows] = useState([]), [total, setTotal] = useState(0), [query, setQuery] = useState(''), [deletedOnly, setDeletedOnly] = useState(false);
  const [offset, setOffset] = useState(0), [busy, setBusy] = useState(false), [confirm, setConfirm] = useState(null), [selected, setSelected] = useState(null);
  const refresh = async () => {
    if (!plugin) return;
    setBusy(true);
    try { const s = await plugin.status(); setStatus(s); if (s.enabled || s.all > 0) { const data = await plugin.list({ offset, limit: 50, query, deletedOnly }); setRows(data.messages); setTotal(data.total); } }
    catch { notify('Could not read the device archive.'); }
    finally { setBusy(false); }
  };
  useEffect(() => { refresh(); }, [offset, query, deletedOnly]);
  useEffect(() => { const onShow = () => refresh(); document.addEventListener('visibilitychange', onShow); return () => document.removeEventListener('visibilitychange', onShow); }, []);
  if (!plugin) return <section className="settings-card"><h2>On this phone</h2><p>Device mode is available in the Android app.</p></section>;
  return <>
    <div className="stats-grid">{[[Trash2, 'Deleted on this phone', status?.deleted || 0, 'Caught from notifications', 'orange'], [Smartphone, 'Messages on this phone', status?.all || 0, 'Never leave the device', 'neutral'], [BellRing, 'Notification access', status ? (status.enabled ? 'On' : 'Off') : '…', status?.enabled ? 'Reading messaging notifications' : 'Needed to read notifications', status?.enabled ? 'blue' : 'orange']].map(([Icon, label, value, caption, color]) => <div className={`stat-card ${color}`} key={label}><div className="stat-top"><span>{label}</span><Icon size={18}/></div><div className="stat-value">{typeof value === 'number' ? value.toLocaleString() : value}<Icon className="stat-watermark" size={43} aria-hidden="true"/></div><p>{caption}</p></div>)}</div>
    {status && !status.enabled && <section className="settings-card"><div className="section-icon"><BellRing size={20}/></div><h2>Allow notification access</h2><p>Device mode reads the notifications WhatsApp, Telegram, and Signal show on this phone and keeps a copy here, on the phone only. When a sender deletes a message while its notification is still showing, the platform replaces the notification text, and the original is kept. Android asks you to allow this in Settings; you can turn it off there at any time.</p><button className="button primary" onClick={() => plugin.openSettings()}>Open notification access settings<ArrowRight size={16}/></button><p className="wizard-smallprint">Only notified messages are seen: chats you have muted, chats open on screen, and messages read on another device before the notification arrived are not captured. Nothing from this mode is uploaded.</p></section>}
    <section className="settings-card"><div className="list-header"><h2>All messages <span className="count-pill">{total}</span></h2><div className="plan-actions"><button className="button secondary compact" disabled={busy} onClick={refresh}><RefreshCw size={14}/>Refresh</button><button className="button secondary compact" onClick={() => setConfirm({ type: 'clear' })} disabled={!status?.all}>Clear device archive</button></div></div>
      <div className="toolbar"><label className="search"><Search size={16}/><input value={query} onChange={e => { setQuery(e.target.value); setOffset(0); }} placeholder="Search messages, people, or chats on this phone…"/></label><label className="checkbox-label"><input type="checkbox" checked={deletedOnly} onChange={e => { setDeletedOnly(e.target.checked); setOffset(0); }}/> Deleted only</label></div>
      {rows.length ? <ul className="device-list">{rows.map(m => <li key={m.id} className={m.deletedAt ? 'deleted' : ''}><button className="device-row" onClick={() => setSelected(m)}><div><strong>{m.sender}{m.isGroup && m.chat !== m.sender ? <span className="muted"> in {m.chat}</span> : ''}</strong><p>{m.deletedAt && !m.text ? 'Deleted before this phone saw it' : m.text}</p><small>{apps[m.package] || m.package} · {when(m.messageTime)}{m.deletedAt ? ` · deleted ${when(m.deletedAt)}` : ''}{m.versions?.length ? ` · ${m.versions.length + 1} versions` : ''}</small></div>{m.deletedAt ? <span className="status deleted"><Trash2 size={12}/>Deleted</span> : m.versions?.length ? <span className="status edited"><Clock3 size={12}/>Edited</span> : null}</button></li>)}</ul>
        : <div className="empty-state"><Smartphone size={28}/><h3>{status?.enabled ? 'Nothing captured yet' : 'Device mode is off'}</h3><p>{status?.enabled ? 'Messages appear here as their notifications arrive.' : 'Allow notification access above to start.'}</p></div>}
      {total > 50 && <div className="pager"><button className="button secondary compact" disabled={!offset} onClick={() => setOffset(Math.max(0, offset - 50))}>Newer</button><span>{offset + 1}–{Math.min(offset + 50, total)} of {total}</span><button className="button secondary compact" disabled={offset + 50 >= total} onClick={() => setOffset(offset + 50)}>Older</button></div>}
    </section>
    <div className="info-strip"><Smartphone size={18}/><p>Device mode keeps everything on this phone and works without an account. It cannot see messages that never produced a notification, and it only knows a message was deleted if the notification was still showing when the sender deleted it. The cloud archive above remains the complete option.</p></div>
    {selected && <Modal title={`${selected.sender}${selected.isGroup && selected.chat !== selected.sender ? ` in ${selected.chat}` : ''}`} onClose={() => setSelected(null)}><p className="modal-description">{apps[selected.package] || selected.package} · sent {when(selected.messageTime)}{selected.deletedAt ? ` · deleted ${when(selected.deletedAt)}` : ''}</p><div className="timeline">{[...(selected.versions || []).map((v, i) => ({ text: v.text, label: `Version ${i + 1}, until ${when(v.until)}` })), { text: selected.text || (selected.deletedAt ? 'The original was not seen by this phone.' : ''), label: selected.deletedAt ? 'Last version before deletion' : 'Current version' }].map((v, i) => <div className="timeline-item" key={i}><strong>{v.label}</strong><div className="message-bubble"><p>{v.text}</p></div></div>)}</div><div className="modal-actions"><button className="button danger-outline" onClick={() => { setConfirm({ type: 'remove', id: selected.id }); setSelected(null); }}><Trash2 size={14}/>Remove from this phone</button></div></Modal>}
    {confirm && <Modal title={confirm.type === 'clear' ? 'Clear the device archive?' : 'Remove this message?'} onClose={() => setConfirm(null)}><p className="modal-description">{confirm.type === 'clear' ? 'Every message captured from notifications on this phone will be removed. This does not affect your cloud archive or the original apps.' : 'This removes the captured copy from this phone only.'}</p><div className="modal-actions"><button className="button secondary" onClick={() => setConfirm(null)}>Cancel</button><button className="button danger" onClick={async () => { if (confirm.type === 'clear') await plugin.clear(); else await plugin.remove({ id: confirm.id }); setConfirm(null); setOffset(0); refresh(); notify(confirm.type === 'clear' ? 'Device archive cleared.' : 'Removed from this phone.'); }}>Confirm</button></div></Modal>}
  </>;
}
