import React, { useEffect } from 'react';
import { ArrowRight, BookOpen, ChevronRight, ExternalLink, Monitor, ShieldCheck } from 'lucide-react';
import { guides, platformGuides, platformOrder } from './guides.mjs';

export function Docs({ slug, onNavigate, onConnect, Platform }) {
  const guide = guides[slug];
  useEffect(() => {
    document.title = guide ? `${guide.title} — Afterword Help` : 'Help & guides — Afterword';
    if (window.location.hash) requestAnimationFrame(() => document.getElementById(window.location.hash.slice(1))?.scrollIntoView());
    return () => { document.title = 'Afterword — Keep the context'; };
  }, [slug]);
  function link(e, href) {
    if (!href.startsWith('/docs') || e.metaKey || e.ctrlKey || e.shiftKey || e.altKey) return;
    e.preventDefault(); onNavigate(href);
  }
  const docLink = (label, href) => <a key={href} href={href} onClick={e => link(e, href)} {...(!href.startsWith('/') ? { target: '_blank', rel: 'noreferrer' } : {})}>{label}{!href.startsWith('/') ? <ExternalLink size={12}/> : <ArrowRight size={13}/>}</a>;
  return <div className="help-center">
    <div className="help-topline"><a href="/docs" onClick={e => link(e, '/docs')}><BookOpen size={15}/>Afterword help</a>{guide && <><ChevronRight size={12}/><span>{guide.platform ? platformGuides[guide.platform].name : guide.category.toLowerCase()}</span></>}</div>
    {!guide ? <><div className="help-heading"><span className="eyebrow">A LITTLE GUIDANCE, EVERY STEP</span><h1>Make yourself at home<span>.</span></h1><p>Connect your accounts, capture your first message, and keep the context.</p></div><a className="quickstart-card" href="/docs/getting-started" onClick={e => link(e, '/docs/getting-started')}><span className="quickstart-icon"><Monitor size={28}/></span><div><span>NEW TO AFTERWORD?</span><h2>Your first archive, step by step</h2><p>Prepare your computer, pair a companion, and check that it works.</p></div><ArrowRight size={23}/></a><h2 className="help-section-title">Connect your accounts</h2><div className="help-platform-grid">{platformOrder.map(p => <a key={p} href={`/docs/${p}`} onClick={e => link(e, `/docs/${p}`)}><Platform platform={p}/><h3>{platformGuides[p].name}</h3><p>{platformGuides[p].summary}</p><span>{platformGuides[p].effort}<ArrowRight size={14}/></span></a>)}</div><h2 className="help-section-title">Once you’re connected</h2><div className="help-extra-grid">{['troubleshooting', 'running', 'privacy'].map(id => <a href={`/docs/${id}`} key={id} onClick={e => link(e, `/docs/${id}`)}><h3>{guides[id].title}<ArrowRight size={15}/></h3><p>{guides[id].description}</p></a>)}</div><div className="help-honesty"><ShieldCheck size={18}/><p>Clear expectations from the start: the guides explain each platform’s coverage, required access, and what happens to your data.</p></div></> : <div className="guide-layout"><article className="guide-article"><header><div className="eyebrow">{guide.category}</div><h1>{guide.title}<span>.</span></h1><p>{guide.description}</p>{guide.platform && <button className="button primary" onClick={() => onConnect(guide.platform)}>Connect {platformGuides[guide.platform].name}<ArrowRight size={15}/></button>}</header>{guide.sections.map(section => <section id={section.id} key={section.id}><h2>{section.title}</h2>{section.paragraphs?.map(p => <p key={p}>{p}</p>)}{section.steps && <ol>{section.steps.map(s => <li key={s}>{s}</li>)}</ol>}{section.bullets && <ul>{section.bullets.map(s => <li key={s}>{s}</li>)}</ul>}{section.code && <pre><code>{section.code}</code></pre>}{section.note && <aside className="guide-note">{section.note}</aside>}{section.links && <div className="guide-links">{section.links.map(r => docLink(r.label, r.url))}</div>}</section>)}<footer><span>Instructions reviewed September 9, 2026. Platform screens may change.</span>{docLink('Back to all guides', '/docs')}</footer></article><aside className="guide-toc"><h2>IN THIS GUIDE</h2><nav aria-label="On this page">{guide.sections.map(s => <a key={s.id} href={`#${s.id}`}>{s.title}</a>)}</nav><div><BookOpen size={18}/><strong>Keep this guide open</strong><p>Use it alongside the connection setup screen.</p><a href="/docs/troubleshooting" onClick={e => link(e, '/docs/troubleshooting')}>Troubleshooting <ArrowRight size={13}/></a></div></aside></div>}
  </div>;
}
