export const platformOrder = ['whatsapp', 'telegram', 'discord', 'signal'];
export const platformGuides = {
  whatsapp: {
    name: 'WhatsApp', mode: 'Linked device · unofficial', effort: 'QR code',
    summary: 'Pair with a QR code from WhatsApp on your phone.',
    coverage: 'Captures ordinary messages, edits, and deletions delivered to your linked device. Uses unofficial software, so WhatsApp changes or account restrictions can interrupt capture.',
    needs: ['Your phone, signed in to WhatsApp', 'An available linked-device slot', 'A computer that can stay on while you capture'],
    finish: ['Keep the companion terminal open until a QR code appears.', 'iPhone: open WhatsApp → Settings → Linked devices → Link a device. Android: open WhatsApp → ⋮ → Linked devices → Link a device.', 'Unlock your phone if asked, then scan the QR code shown on your computer.'],
    exclusions: 'No view-once or disappearing messages, past deleted content, or attachment file downloads.',
    resources: [{ label: 'WhatsApp: link a device', url: 'https://faq.whatsapp.com/1317564962315842/' }, { label: 'Baileys project', url: 'https://github.com/WhiskeySockets/Baileys' }]
  },
  telegram: {
    name: 'Telegram', mode: 'Personal account', effort: 'Phone sign-in + app credentials',
    summary: 'Connect your own Telegram cloud chats with a phone sign-in.',
    coverage: 'Captures ordinary cloud-chat messages, revisions, and deletion events Telegram delivers. Telegram sometimes omits deletion notifications.',
    needs: ['Your phone, signed in to Telegram', 'Your Telegram application API ID and API hash', 'Your two-step verification password, if enabled'],
    finish: ['Open my.telegram.org/apps and sign in. Under API development tools, create an application or use your existing one. Keep its API ID and API hash ready.', 'Enter the API ID and API hash in the companion terminal, followed by your phone number with country code.', 'Enter the confirmation code Telegram sends. It may arrive in the Telegram app. If asked, enter your two-step verification password or email verification code.'],
    exclusions: 'No secret chats, self-destructing messages, historical backfill, or attachment file downloads.',
    resources: [{ label: 'Get your Telegram app credentials', url: 'https://my.telegram.org/apps' }, { label: 'Telegram: application setup', url: 'https://core.telegram.org/api/obtaining_api_id' }, { label: 'Telegram API terms', url: 'https://core.telegram.org/api/terms' }]
  },
  discord: {
    name: 'Discord', mode: 'Personal account · unavailable', effort: 'Personal capture not available yet', available: false,
    summary: 'Personal Discord messages are part of the intended product, but this connection is not available yet.',
    coverage: 'Afterword does not currently capture your personal Discord DMs or group DMs. The earlier server-bot connection does not provide access to your personal inbox.',
    needs: [], finish: [],
    exclusions: 'There is no personal Discord sign-in or pairing flow in this release.',
    resources: [{ label: 'Discord: OAuth2 scopes', url: 'https://docs.discord.com/developers/topics/oauth2' }, { label: 'Discord: local client RPC', url: 'https://docs.discord.com/developers/topics/rpc' }]
  },
  signal: {
    name: 'Signal', mode: 'Linked device · unofficial', effort: 'Extra install + QR code',
    summary: 'Link your phone through the signal-cli companion on your computer.',
    coverage: 'Captures ordinary incoming messages, synced outgoing messages, edits, and remote deletion events received by the linked device. signal-cli is unofficial and must stay current.',
    needs: ['Your phone, signed in to Signal', 'signal-cli installed and available in your terminal', 'An available linked-device slot'],
    finish: ['Install signal-cli before pairing. On macOS with Homebrew, run brew install signal-cli. For Windows and Linux, follow the signal-cli installation guide for your operating system and its Java/runtime requirements.', 'Run signal-cli --version to confirm the terminal can find it. Then start the Afterword companion and wait for its QR code.', 'On your primary phone, open Signal → Settings (your profile) → Linked devices → Link a new device. Unlock if asked, scan the QR code, and approve the link.'],
    exclusions: 'No disappearing or view-once messages, existing Signal Desktop database import, or attachment file downloads.',
    resources: [{ label: 'Install signal-cli', url: 'https://github.com/AsamK/signal-cli#installation' }, { label: 'Homebrew: signal-cli', url: 'https://formulae.brew.sh/formula/signal-cli' }, { label: 'Signal: linked devices', url: 'https://support.signal.org/hc/en-us/articles/360007320551-Linked-Devices' }]
  }
};

const verify = {
  id: 'verify', title: 'Check that your first message arrived',
  paragraphs: ['“Connected” means the platform session is running. A captured message confirms the full route to your archive works. The setup screen checks this automatically; allow up to 30 seconds for status updates.'],
  steps: ['In a covered conversation, send a harmless test message such as “Afterword connection test.” Wait for it to appear in the archive.', 'Edit that message. Open its history in Afterword and check that both versions are present.', 'Delete it in the original app. If the platform delivers the deletion event, Afterword will show Deleted while preserving the captured text.'],
  note: 'Test with your own messages in conversations you are authorized to archive. Afterword does not send a test message for you.'
};
const keepRunning = {
  id: 'keep-running', title: 'Keep capture running',
  paragraphs: ['Leave the companion terminal open and keep the computer awake and connected to the internet. Closing it, sleeping, or unlinking the device interrupts capture. Messages that change during a gap may never be recoverable.'],
  steps: ['To stop, press Ctrl+C in the companion terminal.', 'To resume, reopen a terminal in the companion folder and run the Resume command shown beside that source in Connections.', 'For a second account, create another connection and pair it in another terminal. Afterword assigns separate profiles automatically.'],
  links: [{ label: 'Continuous capture and storage guide', url: '/docs/running' }]
};

export const guides = {
  'getting-started': {
    title: 'Start your first archive', description: 'From a new workspace to your first captured message, one step at a time.', category: 'START HERE',
    sections: [
      { id: 'how-it-works', title: 'Two parts, one archive', paragraphs: ['Afterword is your private web archive. The companion is a small program that runs on your computer, receives messages from the accounts you link, and sends captured copies to that archive.', 'You can browse the archive on your phone. Initial setup needs a Windows, macOS, or Linux computer with a terminal. There is no phone-only installation or background desktop app in this release.'] },
      { id: 'account', title: '1. Create your workspace', steps: ['Choose Create your archive and pick a username and a password with at least 12 characters.', 'If asked, enter the invitation code supplied by your Afterword administrator. This is different from the pairing code you generate later.', 'After signing in, open Connections and choose a platform. Check its coverage and prerequisites before continuing.'], note: 'The signed-out preview contains sample messages. Your own archive starts empty. If you forget your account password, contact the operator of your Afterword instance; self-service email recovery is not available.' },
      { id: 'computer', title: '2. Prepare your computer', steps: ['Install a current Node.js LTS version (22.13 or newer) from nodejs.org. Choose the installer for your computer, then close and reopen your terminal.', 'In the connection setup screen, download the companion ZIP and extract it. Keep this folder somewhere you can find again.', 'Open a terminal in the extracted afterword-companion folder. It should contain package.json and a companion folder.'], links: [{ label: 'Download Node.js', url: 'https://nodejs.org/en/download' }], note: 'macOS: open Terminal, type cd followed by a space, drag the extracted folder into the window, and press Return. Windows: right-click inside the extracted folder and choose Open in Terminal. If PowerShell blocks npm.ps1, use npm.cmd in the commands below; you do not need to weaken your execution policy. Linux: use your file manager’s Open in Terminal action or cd to the folder.' },
      { id: 'pair', title: '3. Pair the companion', paragraphs: ['The setup screen provides two commands with your archive server already filled in. Run the install command once, then the pairing command.'], code: 'npm ci --omit=dev\nnpm start -- pair --server https://YOUR-AFTERWORD-SERVER', steps: ['Copy the short pairing code from the browser into the terminal when asked. Codes expire after 10 minutes and work only once.', 'The companion shows the platform and connection name it has paired. Follow its prompts to sign in or scan a platform QR code.', 'Keep the setup screen open. It will advance when the companion reports that the platform is connected.'], note: 'A pairing code gives the companion access to send data to one source. Treat it as private. Do not paste it into platform chats. The long-lived connection key is stored automatically on your computer and does not go into your command history.' },
      verify, keepRunning,
      { id: 'next', title: 'You control what stays', paragraphs: ['Open Settings to choose how long messages are retained, export your archive, or change your password. Deleting a connection stops syncing but keeps its captured history. Deleting an archived message removes its saved versions from the server.'], links: [{ label: 'Privacy, retention, and deletion', url: '/docs/privacy' }, { label: 'Something not working?', url: '/docs/troubleshooting' }] }
    ]
  },
  discord: {
    title: 'Personal Discord messages', description: platformGuides.discord.summary, category: 'CONNECTION AVAILABILITY', platform: 'discord',
    sections: [
      { id: 'coverage', title: 'Your personal conversations are the goal', paragraphs: ['Afterword is intended for individuals keeping a record of messages delivered to their own accounts, including personal DMs and group DMs.', platformGuides.discord.coverage], note: 'Personal Discord capture is unavailable. You do not need a server, a bot token, or permission to install a bot.' },
      { id: 'access', title: 'Why there is no Connect button yet', paragraphs: ['Ordinary Discord sign-in does not grant an app access to all of your message content. Discord documents messages.read for its local client RPC interface; RPC access is restricted to approved partners, with limited testing access.', 'Afterword has not obtained or verified that access. A personal connector must be implemented and tested for new messages, edits, and deletions before this page can offer account linking. A user-installed bot does not provide the missing inbox access.'], links: platformGuides.discord.resources },
      { id: 'current-release', title: 'What to expect in this release', bullets: ['No Discord developer setup or server selection is required from you.', 'No personal Discord session is connected, and no personal Discord messages are being archived.', 'The server-bot setup path has been withdrawn. An old Discord source or sample message is not proof of personal-account support.', 'Existing archived records remain available. Other personal-account connections can still be set up from their guides.'], links: [{ label: 'Connect your Telegram account', url: '/docs/telegram' }, { label: 'Link your Signal account', url: '/docs/signal' }, { label: 'Link your WhatsApp account', url: '/docs/whatsapp' }] }
    ]
  },
  ...Object.fromEntries(platformOrder.filter(platform => platform !== 'discord').map(platform => {
    const p = platformGuides[platform];
    return [platform, {
      title: `Connect ${p.name}`, description: p.summary, category: 'CONNECTION GUIDE', platform,
      sections: [
        { id: 'coverage', title: 'What this connection covers', paragraphs: [p.coverage], note: p.exclusions },
        { id: 'before', title: 'Before you start', bullets: [...p.needs, 'Node.js 22.13 or newer on the computer running your companion'], links: [{ label: 'First time? Prepare your computer', url: '/docs/getting-started#computer' }] },
        { id: 'platform-setup', title: `Prepare ${p.name}`, steps: p.finish, links: p.resources },
        { id: 'pair', title: 'Pair with your Afterword workspace', steps: [`In Connections, choose Connect ${p.name}. Review the checklist, name your connection, and continue.`, 'Download and extract the companion ZIP. Open a terminal in its folder, then copy the install and pairing commands from the setup screen.', 'Enter the short Afterword pairing code in the terminal. The companion selects the right platform automatically; finish the sign-in steps or scan the QR code it displays.'], note: 'You do not enter your platform password into the Afterword website. Platform credentials and sessions stay on the computer running your companion.' },
        verify,
        { id: 'fixes', title: `If ${p.name} does not connect`, bullets: platform === 'telegram' ? ['API credentials rejected: the API ID is numeric and the API hash comes from API development tools; neither is a BotFather token.', 'No confirmation code: check the Telegram service conversation on your phone. Do not repeatedly request codes; Telegram can impose a waiting period.', 'Wrong saved app credentials: run the companion’s credentials command for that profile, then resume. If Telegram reports a revoked session, follow the relinking instructions in Troubleshooting.'] : platform === 'signal' ? ['signal-cli not found: install it, reopen the terminal, and confirm signal-cli --version works. Installing Signal Desktop alone does not install signal-cli.', 'QR expires: restart the companion and use the new QR code. Scan using Linked devices on your primary phone, not the camera app.', 'Device limit or revoked session: remove an unused device in Signal, then follow the relinking guide. Update signal-cli when Signal changes its protocol.'] : ['QR not visible: keep the terminal wide enough and wait for the companion to finish connecting. If it expires, use the refreshed code.', 'QR scan fails: use WhatsApp’s Linked devices scanner on your primary phone. Make sure both devices have internet access.', 'Logged out or device removed: stop the companion and follow the relinking guide. Repeated failures after an update may need a newer Baileys/companion release.'], links: [{ label: 'Connection states, retries, and relinking', url: '/docs/troubleshooting' }] },
        keepRunning
      ]
    }];
  })),
  troubleshooting: {
    title: 'Get a connection back on track', description: 'Find the status you see, then take the next step.', category: 'TROUBLESHOOTING',
    sections: [
      { id: 'states', title: 'Understand connection status', bullets: ['Ready to pair: a source exists, but the companion has not paired. Choose Continue setup.', 'Finish sign-in: the companion paired with Afterword; complete the platform login or QR scan in the terminal.', 'Capturing messages: the platform session reports connected and the companion checked in recently. Send a test message to verify delivery.', 'Companion offline: Afterword has not heard from the companion for 90 seconds. Check the computer and run the Resume command.', 'Reconnecting: keep the process open while it retries the platform connection.', 'Paused: new events reaching the archive are discarded. Resume to capture new activity; paused events are not recovered afterward.', 'Needs attention: read the terminal and the platform guide. A rejected event remains in the local queue for diagnosis.'], note: 'A green connection status proves the session is running, not that every platform event is guaranteed to arrive.' },
      { id: 'pairing', title: 'Pairing code expired, used, or lost', steps: ['Open Connections → Continue setup for the same source. You do not need to create another source.', 'Generate a new pairing code. The old unused code stops working.', 'Run the pairing command again and enter the new code. Redemption replaces that source’s previous companion key, so stop its old companion first.'], note: 'A code is valid for ten minutes and one redemption. After repeated incorrect attempts, wait 15 minutes before trying again. If pairing succeeded but the terminal lost the response, generate another code; do not share screenshots containing codes.' },
      { id: 'terminal', title: 'Terminal and installation errors', bullets: ['“node” or “npm” not found: install Node.js LTS, then reopen the terminal.', 'PowerShell refuses npm.ps1: run npm.cmd ci --omit=dev and npm.cmd start -- … instead. Keep the rest of each command the same.', '“package.json not found”: move into the extracted afterword-companion folder before running the command.', '“Unsupported engine”: update Node.js to 22.13 or newer.', 'Download or dependency install failed: check internet/proxy access and rerun npm ci --omit=dev. Do not run the companion as administrator just to work around permissions.', 'Certificate/network error: confirm the server address opens over HTTPS in a browser. Do not disable TLS certificate checks.'] },
      { id: 'credentials', title: 'Replace Telegram application credentials', paragraphs: ['Use this when the companion saved a mistyped Telegram API ID/hash. It updates only the platform credentials for the chosen profile; your queue, archive connection, and message history stay intact.'], code: 'npm start -- credentials YOUR-PROFILE\nnpm start -- run YOUR-PROFILE', note: 'Get the exact profile name from the source’s Resume instructions. Phone codes and two-step passwords are requested only when the platform needs them; they are not saved as configuration.' },
      { id: 'relink', title: 'A platform unlinked your device', paragraphs: ['Archive pairing and platform linking are separate. A new Afterword code cannot repair a WhatsApp or Signal device session the platform revoked. First stop the companion with Ctrl+C.'], steps: ['Open the linked-device/session list in the platform app and remove the old companion session if it is still listed.', 'Use the Relink command below with the exact profile shown in Connections. It clears only the selected platform session after you type RELINK; it preserves the archive key and queued events.', 'Resume that profile and complete the fresh QR scan or Telegram sign-in. No new Afterword source is required.'], code: 'npm start -- relink YOUR-PROFILE\nnpm start -- run YOUR-PROFILE', note: 'Relinking cannot restore edits or deletions missed while the collector was disconnected.' },
      { id: 'missing', title: 'Connected, but a message is missing', bullets: ['Confirm you are viewing your signed-in archive, not sample data, and clear search/platform filters.', 'Use a new ordinary text message in a covered conversation. Content from before capture started is not backfilled.', 'Check that the computer stayed awake, that the source is not paused, and that the terminal reports no errors.', 'Signal/WhatsApp disappearing or view-once messages and Telegram secret/self-destructing messages are excluded. Personal Discord capture is not available in this release.', 'If the archive server was down, received events stay queued locally and upload after it recovers. Activity never delivered to the companion is not in that queue.', 'Telegram may omit deletion events. Attachment filenames can appear without downloadable files because this release stores metadata only.'] },
      { id: 'support', title: 'What to include in a support report', bullets: ['Platform, operating system, Node.js version, and the status shown in Connections.', 'Whether the issue is pairing, platform sign-in, or capturing a new test message.', 'A short description of the error with private information removed.'], note: 'Never include a bot token, pairing code, API hash, session file, queue key, or private conversation text. Contact the operator of your Afterword instance; this release does not have an in-app support inbox.' }
    ]
  },
  running: {
    title: 'Keep your archive up to date', description: 'Resume safely, connect more accounts, and understand what stays on your computer.', category: 'EVERYDAY USE',
    sections: [keepRunning,
      { id: 'profiles', title: 'One profile for each source', paragraphs: ['Pairing assigns a unique profile such as telegram-a1b2c3d4. This keeps two accounts or sources from mixing local sessions or queued messages. Use the exact Resume command displayed in Connections.'], code: 'npm start -- run telegram-a1b2c3d4', note: 'Run only one process per profile. Each additional source needs a separate terminal or supervised process. The companion folder contains the program; your profile data lives outside it, so replacing the program folder does not erase your session.' },
      { id: 'always-on', title: 'For continuous capture', paragraphs: ['For the simplest setup, leave a dedicated terminal open on a computer that stays awake. Your web browser does not need to stay open. For unattended operation, use an operating-system process supervisor after completing the first sign-in interactively.'], bullets: ['Linux: use a user systemd service with the absolute Node executable, companion/index.mjs run YOUR-PROFILE, a working directory pointing to the extracted folder, Restart=on-failure, RestartSec=10, and UMask=0077.', 'macOS: use a LaunchAgent with the same executable, script, profile, working directory, and restricted file permissions. The companion does not install a LaunchAgent automatically.', 'Windows: use Task Scheduler under your own user account with node.exe, the absolute script path, and run YOUR-PROFILE. Set the working directory to the extracted folder. Complete QR/sign-in first.'], note: 'This release does not ship a desktop tray app or automatic background-service installer. A supervisor restarts stopped processes; it cannot solve expired logins or scan QR codes for you.' },
      { id: 'updates', title: 'Update without losing your history', steps: ['Stop the companion using Ctrl+C.', 'Download the latest ZIP from a connection setup screen and extract it to a new folder.', 'Run npm ci --omit=dev in that folder, then use your existing profile’s Resume command.', 'For Signal, update signal-cli separately and confirm signal-cli --version works.'], note: 'Your cloud archive and profiles are separate from the downloaded program. Keep your profile files in place unless you intentionally want to unlink or remove local data.' },
      { id: 'storage', title: 'Where local data lives', paragraphs: ['On macOS and Linux, profiles live under ~/.afterword/. On Windows, look inside .afterword in your user home folder. Each profile contains a restricted config.json, an encrypted retry queue, its local encryption key, and any platform session files.'], bullets: ['The local queue keeps captured events during an archive outage and removes acknowledged deliveries.', 'Some local metadata is retained to correlate edits. Cloud retention does not automatically erase this local metadata.', 'Protect your computer and backups: possession of the local queue and its key allows decryption.'], links: [{ label: 'Delete local and cloud data', url: '/docs/privacy#deletion' }] }
    ]
  },
  privacy: {
    title: 'Your archive, your controls', description: 'Understand access, encryption, retention, and deletion before you connect.', category: 'PRIVACY & COVERAGE',
    sections: [
      { id: 'access', title: 'What you authorize', paragraphs: ['Connect only accounts and conversations you are authorized to retain. The current collectors capture covered conversations the linked account or bot receives; per-chat allowlists are not available in this release.', 'The archive can preserve a captured copy after another participant edits or deletes the original. Set expectations with the people or communities whose conversations you archive.'] },
      { id: 'encryption', title: 'Where messages and credentials go', paragraphs: ['Platform credentials and sessions are stored on the computer running your companion. Captured message events are sent to your Afterword server over HTTPS. Message bodies and related names are encrypted in its database.', 'The server holds the encryption key and decrypts messages for search and display. This is encryption at rest, not end-to-end encrypted cloud storage. Your Afterword operator controls the server and its backups.'] },
      { id: 'retention', title: 'Choose how long to keep messages', paragraphs: ['Settings → Archive retention lets you choose 7, 30, or 90 days, one year, or until you delete them. Age is measured from the first capture, and saved/bookmarked messages follow the same policy.', 'Shortening retention immediately removes older messages. Export first if you need a copy. A deletion in the source app does not itself remove the saved archive.'] },
      { id: 'deletion', title: 'Disconnecting and deleting are different', bullets: ['Pause: stops storing newly delivered events until resumed. Paused events are discarded.', 'Disconnect source: revokes its archive key while preserving captured cloud history. Also unlink the companion in the platform app if you want to end platform access.', 'Delete archived message: removes its cloud revisions and prevents queued retries from restoring them. It does not delete the message in the original app.', 'Delete account: after password confirmation, removes its messages, connections, and sessions from the running archive database.', 'Remove local data: stop the companion, revoke/unlink the platform session, then remove that source’s profile folder. Cloud deletion does not delete files or backups on your computer.'], note: 'Exports and backups are separate copies. The initial deployment has no automatic backup deletion service; the instance operator must manage any backups they create.' },
      { id: 'limits', title: 'What cannot be recovered', bullets: ['A message or earlier version the companion never received.', 'Changes missed while the computer, platform session, or network was unavailable.', 'Content outside a platform connection’s documented scope.', 'Disappearing/view-once content excluded by the collector, or attachment file bodies that were never downloaded.'], links: platformOrder.map(p => ({ label: `${platformGuides[p].name} coverage`, url: `/docs/${p}` })) }
    ]
  }
};
